<a href="https://colab.research.google.com/github/shamim237/Bangla-Sign-digit-recognition/blob/main/SVM_DenseNet121.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import glob
import cv2
import tensorflow as tf

from keras.models import Model, Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D,  GlobalAveragePooling2D
from keras.layers.normalization import BatchNormalization
import os
import seaborn as sns
from keras.applications.vgg16 import VGG16
from tensorflow.keras.optimizers import RMSprop, Adam, SGD
from keras.models import load_model, Model

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
SIZE = 128

In [ ]:
# train_images = []
# train_labels = [] 

# for directory_path in glob.glob("/content/drive/MyDrive/digit_final_data/train/*"):
#     label = directory_path.split("/")[-1]
#     print(label)
#     for img_path in glob.glob(os.path.join(directory_path, "*.JPG")):
#         print(img_path)
#         img = cv2.imread(img_path, cv2.IMREAD_COLOR)       
#         img = cv2.resize(img, (SIZE, SIZE))
#         img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
#         train_images.append(img)
#         train_labels.append(label)

# #Convert lists to arrays        
# train_images = np.array(train_images)
# train_labels = np.array(train_labels)

In [ ]:
import pickle
# pick_in = open('/content/drive/MyDrive/Colab Notebooks/Thesis/data_train.pickle', 'wb')
# pickle.dump(train_images, pick_in)
# pick_in.close()

In [ ]:
pick_in = open('/content/drive/MyDrive/Colab Notebooks/Thesis/data_train.pickle', 'rb')
train_images = pickle.load(pick_in)
pick_in.close()

In [ ]:
pick_in = open('/content/drive/MyDrive/Colab Notebooks/Thesis/data_train_labels.pickle', 'rb')
train_labels = pickle.load(pick_in)
pick_in.close()

In [ ]:
# import pickle
# pick_in = open('/content/drive/MyDrive/Colab Notebooks/Thesis/data_train_labels.pickle', 'wb')
# pickle.dump(train_labels, pick_in)
# pick_in.close()

In [ ]:
# test_images = []
# test_labels = [] 

# for directory_path in glob.glob("/content/drive/MyDrive/digit_final_data/validation/*"):
#     im_label = directory_path.split("/")[-1]
#     for img_path in glob.glob(os.path.join(directory_path, "*.JPG")):
#         img = cv2.imread(img_path, cv2.IMREAD_COLOR)
#         img = cv2.resize(img, (SIZE, SIZE))
#         img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
#         test_images.append(img)
#         test_labels.append(im_label)

# #Convert lists to arrays                
# test_images = np.array(test_images)
# test_labels = np.array(test_labels)

In [ ]:
# pick_in = open('/content/drive/MyDrive/Colab Notebooks/Thesis/data_test.pickle', 'wb')
# pickle.dump(test_images, pick_in)
# pick_in.close()

In [ ]:
pick_in = open('/content/drive/MyDrive/Colab Notebooks/Thesis/data_test.pickle', 'rb')
test_images = pickle.load(pick_in)
pick_in.close()

In [ ]:
# pick_in = open('/content/drive/MyDrive/Colab Notebooks/Thesis/data_test_label.pickle', 'wb')
# pickle.dump(test_labels, pick_in)
# pick_in.close()

In [ ]:
pick_in = open('/content/drive/MyDrive/Colab Notebooks/Thesis/data_test_label.pickle', 'rb')
test_labels = pickle.load(pick_in)
pick_in.close()

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(test_labels)
test_labels_encoded = le.transform(test_labels)
le.fit(train_labels)
train_labels_encoded = le.transform(train_labels)

In [ ]:
x_train, y_train, x_test, y_test = train_images, train_labels_encoded, test_images, test_labels_encoded

In [ ]:
# x_train = np.load('/content/drive/MyDrive/Colab Notebooks/x_train(RF_cnn).npy')
# x_test = np.load('/content/drive/MyDrive/Colab Notebooks/x_test(RF_cnn).npy')
# y_train = np.load('/content/drive/MyDrive/Colab Notebooks/y_train(RF_cnn).npy')
# y_test = np.load('/content/drive/MyDrive/Colab Notebooks/y_test(RF_cnn).npy')

In [ ]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
from keras.utils import to_categorical
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

In [ ]:
# dense_model = tf.keras.applications.densenet.DenseNet121(weights='imagenet', include_top=False, input_shape=(128, 128, 3))

In [ ]:
# x = dense_model.output  #
# x = GlobalAveragePooling2D()(x) # convert data into flattern for Dense layer

# #x = Flatten()(x) #add fully connected layer
# x = Dense(1024, activation='relu')(x)
# predictions = Dense(10, activation='softmax')(x)
# # lets build the model
# model = Model(inputs=dense_model.input, outputs=predictions)

In [ ]:
# for layer in model.layers[:40]:
#    layer.trainable = False
# for layer in model.layers[:40]:
#    layer.trainable = True

In [ ]:
#model.summary()

In [ ]:
# model.compile(optimizer=Adam(lr=0.0001), loss='categorical_crossentropy',  metrics=['accuracy'])
# history= model.fit(x_train, y_train, 
#                    #steps_per_epoch= 250, 
#                    validation_data= (x_test, y_test), 
#                    verbose = 1, 
#                    epochs = 10, 
#                    batch_size = 64)

In [ ]:
#model.save('/content/drive/MyDrive/Colab Notebooks/Thesis/DenseNet121_ML.h5')

In [ ]:
base_model = load_model('/content/drive/MyDrive/Colab Notebooks/Thesis/DenseNet121_ML.h5')

In [ ]:
base_model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 128, 128, 3) 0                                            
__________________________________________________________________________________________________
zero_padding2d (ZeroPadding2D)  (None, 134, 134, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1/conv (Conv2D)             (None, 64, 64, 64)   9408        zero_padding2d[0][0]             
__________________________________________________________________________________________________
conv1/bn (BatchNormalization)   (None, 64, 64, 64)   256         conv1/conv[0][0]                 
______________________________________________________________________________________________

In [ ]:
layer = 'conv5_block16_concat'

x = base_model.get_layer(layer).output
x = GlobalAveragePooling2D()(x) # convert data into flattern for Dense layer

model1 = Model(inputs = base_model.input, outputs = x)

In [ ]:
feature_extractor = model1.predict(x_train)

In [ ]:
features = feature_extractor.reshape(feature_extractor.shape[0], -1)

In [ ]:
X_for_SVM = features

In [ ]:
from sklearn.svm import SVC
SVM_model = SVC(kernel = 'rbf')

In [ ]:
SVM_model.fit(X_for_SVM, np.argmax(y_train, axis=1))

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
score = SVM_model.score(X_for_SVM, np.argmax(y_train,axis=1))
print(score)

1.0


In [ ]:
X_test_feature = model1.predict(x_test)

In [ ]:
X_test_features = X_test_feature.reshape(X_test_feature.shape[0], -1)

In [ ]:
prediction_SVM = SVM_model.predict(X_test_features)

In [ ]:
prediction_SVM = le.inverse_transform(prediction_SVM)

In [ ]:
from sklearn import metrics
print ("Accuracy = ", metrics.accuracy_score(test_labels, prediction_SVM))

Accuracy =  0.9783653846153846


In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(test_labels, prediction_SVM)
print(cm)

[[186   1   0   0   0   0  13   0   1  11]
 [  0 118   0   0   0   0   0   0   0   0]
 [  0   0 106   0   0   0   0   0   0   0]
 [  0   0   0 106   0   0   0   0   0   0]
 [  0   0   0   0 108   0   0   0   0   0]
 [  0   0   0   0   0 108   0   0   1   0]
 [  0   0   0   0   0   0 104   0   0   0]
 [  0   0   0   0   0   0   0 103   0   0]
 [  0   0   0   0   0   0   0   0 106   0]
 [  0   0   0   0   0   0   0   0   0 176]]
